name: 'GKE Login Action'
description: 'Performs login to GCP/GKE and configures kubectl accordingly'
inputs:
  gcp-project-id:
    description: 'GCP project ID'
    required: false
  gcp-service-account-key:
    description: 'GCP service account key'
    required: false
  gke-cluster:
    description: 'Cluster ID in GKE'
    required: false
  gke-zone:
    description: 'Zone to use in GKE'
    default: 'europe-west3-b'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Login into GCP and configure kubectl to use GKE
      env:
        GCP_PROJECT_ID: ${{ inputs.gcp-project-id }}
        GCP_SERVICE_ACCOUNT_KEY: ${{ inputs.gcp-service-account-key }}
        GKE_CLUSTER: ${{ inputs.gke-cluster }}
        GKE_ZONE: ${{ inputs.gke-zone }}
      run: |
        GCP_SERVICE_ACCOUNT="$(echo "$GCP_SERVICE_ACCOUNT_KEY" | jq -r .client_email)"

        if [[ -z "$GCP_PROJECT_ID" ]]; then
          GCP_PROJECT_ID="$(echo "$GCP_SERVICE_ACCOUNT_KEY" | jq -r .project_id)"
        fi

        gcloud --quiet config set project "$GCP_PROJECT_ID"
        echo "$GCP_SERVICE_ACCOUNT_KEY" | gcloud --quiet auth activate-service-account $GCP_SERVICE_ACCOUNT --project="$GCP_PROJECT_ID" --key-file -
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      shell: bash
